name: Build 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install
        working-directory: ./Zadanie_5_Frontend/frontned-app

      - name: Build Docker image
        run: docker build -t deploy_azure_app/your-frontend-image:latest -f Zadanie_10_Azure_Deploy/frontend_docker.dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push deploy_azure_app/your-frontend-image:latest